import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ToggleMode } from "@/components/ui/toggle-mode";
import { Toaster } from "@/components/ui/sonner";
import { Lang, locales } from "@/proxy";
import Header from "@/lang/components/header";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export function generateStaticParams() {
	return locales.map((lang) => ({ lang }));
}

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ lang: Lang }>;
}>) {
	const { lang } = await params;

	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<Header lang={lang}/>
					<div className="container mx-auto my-10">{children}</div>
					<ToggleMode />
					<Toaster richColors theme="light" toastOptions={{}} />
				</ThemeProvider>
			</body>
		</html>
	);
}
